import type { Metadata } from "next";
import localFont from "next/font/local";
import { Style_Script, Smooch_Sans } from "next/font/google";
import { Toaster } from "sonner";
import { QueryProvider } from "../providers/QueryProvider";
import { AudioProvider } from "../providers/AudioProvider";
import "./globals.css";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const styleScript = Style_Script({
  subsets: ["latin"],
  variable: "--font-style-script",
  weight: "400",
});

const smoochSans = Smooch_Sans({
  subsets: ["latin"],
  variable: "--font-smooch-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Tru South King",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${styleScript.variable} ${smoochSans.variable} antialiased m-0 p-0 w-screen min-h-screen overflow-x-hidden loading`}
      >
        <QueryProvider>
          <AudioProvider>
            {children}
            <Toaster richColors position="top-right" />
          </AudioProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
